name: stylesync

version: '3.8'

services:
  postgres-dev:
    image: postgres:15
    container_name: postgres-dev
    restart: "no"
    environment:
      POSTGRES_DB: stylesync_dev
      POSTGRES_USER: stylesync
      POSTGRES_PASSWORD: 5&cT_5;j!c
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stylesync -d stylesync_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
    driver: local

networks:
  network:
    driver: bridge
